# Generated by Django 4.2 on 2023-08-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_userinfo_age_alter_userinfo_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrettyNum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="手机号")),
                (
                    "price",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="价格"
                    ),
                ),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(2, "二级"), (4, "四级"), (1, "一级"), (3, "三级")],
                        default=1,
                        verbose_name="级别",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(2, "未使用"), (1, "已占用")], default=2, verbose_name="状态"
                    ),
                ),
            ],
        ),
    ]
