# Generated by Django 4.2 on 2023-09-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_prettynum"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="original_images/")),
                ("processed_image", models.ImageField(upload_to="processed_images/")),
            ],
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "一级"), (4, "四级"), (2, "二级"), (3, "三级")],
                default=1,
                verbose_name="级别",
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "已占用"), (2, "未使用")], default=2, verbose_name="状态"
            ),
        ),
    ]
